CREATE LOGIN [ROOTO]
    WITH PASSWORD = N'z{u=k?up{|qxr+qfkKTtqczcmsFT7_&#$!~<egRtrwwk0#o@', SID = 0xEB35FDBEC221E44FBABD072EBE19A7AF, DEFAULT_DATABASE = [CafeteriaDb], DEFAULT_LANGUAGE = [us_english];

